
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../component/common/header/header";
import SessionProviderWrapper from "./SessionProviderWrapper";
import { signOut } from "next-auth/react";

// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session
}: Readonly<{
  children: React.ReactNode;
  session : any
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <SessionProviderWrapper session={session}>
        <Header />
        {children}
      </SessionProviderWrapper>
      </body>
    </html>
  );
}
